### ISSUE TITLE
Broken link in repo read me

### ISSUE THREAD

**Issue by amosmachora** [palladiumkenya/openmrs-config-kenyaemr#584]
There seems to be a broken link inthe repository readme. I think its supposed to redirect the user to another repo https://github.com/openmrs/openmrs-distro-kenyaemr that throws a 404 error when visited. You can assign me the issue and the correct repo link if its supposed to be there and i will be on it.

Here is a screenshot.
![image](https://github.com/palladiumkenya/openmrs-config-kenyaemr/assets/81857018/312ed7f4-0842-453b-802e-bcc67129450e).

Thanks.

**Comment by ojwanganto** [comment]
Which repo is this?

**Comment by amosmachora** [comment]
This repo`s readme.md file. see [here](https://github.com/palladiumkenya/openmrs-config-kenyaemr?tab=readme-ov-file#readme) click on the first link.
